"use client";
import { ReactLenis } from "@studio-freight/react-lenis";
import "./globals.css";
import ProgressBar from "@/components/ProgressBar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    return (
        <ReactLenis root>
            <html lang="en">
                <body className="scrollbar-hide bg-fixed bg-bromo bg-cover bg-center backdrop-blur-sm">
                    {/* <ProgressBar /> */}
                    {children}
                </body>
            </html>
        </ReactLenis>
    );
}
